#!/usr/bin/env python3
from pathlib import Path
import sys

REQUIRED = {
    "models/football/qa/check_authority_consistency.py": [
        "FOOTBALL AUTHORITY QA FAIL",
        "Football C authority and C2 comparison semantics are internally consistent",
        "def c2_ranking_key",
        "SUPPORTED BURDEN NOT INDEPENDENTLY FROZEN",
    ],
    "models/football/procedures/FOOTBALL_PRE_DECISION_SPEC.md": [
        "RETIRED FOR NEW FOOTBALL C PRODUCTION",
    ],
    "models/football/procedures/FOOTBALL_STEP2_EXECUTION_SPEC.md": [
        "RETIRED FOR NEW FOOTBALL C PRODUCTION",
    ],
    "models/football/prompts/05_NORMAL_CHAT_FOOTBALL_C.md": [
        "RETIRED — DO NOT USE FOR NEW PRODUCTION",
        "LAUNCHER RETIRED — USE CURRENT FOOTBALL C COMMAND ROUTER",
    ],
    "models/football/prompts/README.md": [
        "Short commands — preferred",
        "/sweep",
        "/rank",
        "/xi",
        "/live",
        "/audit",
        "/report",
        "/help",
    ],
    "models/football/prompts/COMMAND_ALIASES.md": [
        "ACTIVE ROUTER CONTRACT",
        "/sweep",
        "/rank",
        "/xi",
        "/live",
        "/audit",
        "/report",
        "/help",
        "first non-whitespace token",
        "project-level text commands",
    ],
    "models/football/prompts/06_NORMAL_CHAT_REPORT.md": [
        "Command alias:** `/report`",
        "read/report launcher only",
        "must not",
        "Default `/report`",
        "Refresh modifier",
    ],
    "models/football/prompts/sweep.md": ["# /sweep", "00_NORMAL_CHAT_AISCORE_FETCH.md"],
    "models/football/prompts/rank.md": ["# /rank", "01_WORK_DAILY_SWEEP.md"],
    "models/football/prompts/xi.md": ["# /xi", "02_NORMAL_CHAT_XI_ODDS.md"],
    "models/football/prompts/live.md": ["# /live", "03_NORMAL_CHAT_LIVE.md"],
    "models/football/prompts/audit.md": ["# /audit", "04_WORK_POST_SLATE_AUDIT.md"],
    "models/football/prompts/report.md": ["# /report", "06_NORMAL_CHAT_REPORT.md"],
    "models/football/procedures/FOOTBALL_WOMENS_TOP_FLIGHT_COVERAGE.md": [
        "mandatory Step-0 coverage invariant",
        "Mandatory discovery class",
        "HANDOFF INCOMPLETE — WOMEN TOP-FLIGHT COVERAGE GAP",
        "women_top_flight_raw_count",
        "women_top_flight_disposition_manifest",
        "Researchability parity",
        "Senior Women's Top Flight = true",
    ],
    "models/football/procedures/FOOTBALL_BURDEN_COMPLETION_SELECTION.md": [
        "mandatory Football C Step-1 selection layer",
        "Where does the goal that clears the supported burden come from?",
        "CARRIER_LED",
        "Burden stall risk",
        "C-PASS carrier contradiction",
        "at most **2 routine FOLLOW fixtures per exact kickoff minute**",
    ],
    "models/football/procedures/FOOTBALL_COMPETITION_RELIABILITY_MEMORY.md": [
        "mandatory persistent Step-0 memory",
        "Competition Reliability",
        "Competition Reliability Events",
        "latest 10 countable observations",
        "CAUTION caps a current A fixture to **B**",
        "Normal DEMOTED treatment is **C / operational exclusion**",
        "one B-grade probation fixture per sweep",
        "must **never** use:",
        "Activation / no-backfill boundary",
        "starts `UNPROVEN`",
    ],
    "models/football/airtable/FOOTBALL_COMPETITION_RELIABILITY_AIRTABLE.md": [
        "tbl1KShXxXErUdVKW",
        "tblD0ZHqT772H25Uv",
        "Operational Grade",
        "Competition Reliability State",
        "Operational Excluded Count",
        "Capacity Deferred Count",
    ],
    "models/football/airtable/FOOTBALL_COVERAGE_AIRTABLE.md": [
        "Senior Women's Top Flight",
        "Senior women's domestic top-flight",
        "Historical Football A/v0.2.x country/league blanket overlays are **not** current authority",
        "C Supported Line",
        "C2 Supported Line",
    ],
    "models/football/airtable/FOOTBALL_DECISION_STATE_AIRTABLE.md": [
        "Official model:** Football C",
        "Current Completion Mode",
        "Current Completion Quality",
        "Current Continuation Quality",
        "Current Opponent Leakage",
        "Current Stall Risk",
        "C supported line",
        "C2 supported line",
        "C2 shadow action",
    ],
    "models/football/procedures/FOOTBALL_OPERATIONAL_VIABILITY_GATE.md": [
        "mandatory Step-0 production gate",
        "operational_viability_grade = A / B / C / D",
        "LOW OPERATIONAL OBSERVABILITY — STEP0 EXCLUDED",
        "MAX_WORK_ADMISSIONS = 15",
        "OPERATIONAL CAPACITY DEFERRED — STEP0",
        "B-grade C-FOCUS: maximum routine lane is RESERVE",
        "Persistent competition reliability cap",
        "history may never promote B->A or C->B",
        "senior women\'s domestic top-flight",
    ],
    "models/football/procedures/FOOTBALL_TOURNAMENT_INCENTIVE_INTEGRITY.md": [
        "Assessment completion hard gate",
        "ASSESSMENT INCOMPLETE — TOURNAMENT INCENTIVE CHECK MISSING",
        "DECISION BLOCKED — TOURNAMENT INCENTIVE RECHECK MISSING",
        "ASSESSMENT BLOCKED — TOURNAMENT INCENTIVE UNRESOLVED",
        "DECISION BLOCKED — TOURNAMENT INCENTIVE UNRESOLVED",
        "LIVE DECISION BLOCKED — TOURNAMENT INCENTIVE EPOCH MISSING",
        "LIVE DECISION BLOCKED — TOURNAMENT INCENTIVE UNRESOLVED",
        "ASSESSMENT BLOCKED — TOURNAMENT INCENTIVE UNRESOLVED",
        "DECISION BLOCKED — TOURNAMENT INCENTIVE UNRESOLVED",
        "Blooming-type failure guard",
    ],
    "models/football/prompts/00_NORMAL_CHAT_AISCORE_FETCH.md": [
        "RESEARCHABLE_SENIOR_PRODUCTION",
        "INSUFFICIENT RESEARCHABILITY — STEP0 EXCLUDED",
        "Protected senior competition classes",
        "Operational viability gate — mandatory",
        "OPERATIONAL CAPACITY DEFERRED — STEP0",
        "admitted fixture count is <= 15",
        "Competition reliability memory — mandatory",
        "competition_reliability_state",
        "DEMOTED: default C",
        "Mandatory senior-block discovery",
        "senior women\'s domestic top-flight",
        "women_top_flight_raw_count",
        "women_top_flight_disposition_manifest",
        "WOMEN TOP-FLIGHT COVERAGE GAP",
        "Command alias:** `/sweep`",
    ],
    "models/football/CURRENT_MODEL.md": [
        "Active official model:** Football **C**",
        "Shadow challenger:** Football **C2**",
        "COMMON FOOTBALL FACT FREEZE",
        "tournament_incentive_required",
        "Football C's board is the only board that can feed official Step-2 exposure.",
        "models/football/engine/",
        "operational viability gate",
        "Normal Work admission is capped at 15",
        "COMPETITION RELIABILITY MEMORY",
        "Historical competition reliability may only cap/demote current viability",
        "women\'s domestic top-flight",
        "WOMEN TOP-FLIGHT COVERAGE GAP",
    ],
    "models/football/production/FOOTBALL_C.md": [
        "**Intake:** RESEARCHABLE_SENIOR_PRODUCTION",
        "INSUFFICIENT RESEARCHABILITY — STEP0 EXCLUDED",
        "one mandatory fresh fixture-specific public-web football research pass",
        "Market-history/odds lookup does not satisfy the football-research requirement",
        "H2H is mandatory context when usable",
        "PRICE DECAY != THESIS DECAY",
        "operational viability gate",
        "Only operational grade A/B fixtures enter the normal Football C board",
        "burden-completion",
        "Two-sidedness is one completion mode",
    ],
    "models/football/prompts/01_WORK_DAILY_SWEEP.md": [
        "sweep_scope_mode=RESEARCHABLE_SENIOR_PRODUCTION",
        "Football C Official + C2 Shadow Board",
        "Common evidence freeze",
        "Football C official board",
        "Football C2 shadow board",
        "C2 shadow board never substitutes for C",
        "FOOTBALL_ENGINE_C_INPUT",
        "FOOTBALL_ENGINE_C2_INPUT",
        "Operational follow-through guard",
        "ASSESSMENT INCOMPLETE — TOURNAMENT INCENTIVE CHECK MISSING",
        "tournament_incentive_required",
        "INCENTIVE-INCOMPLETE",
        "ASSESSMENT BLOCKED — TOURNAMENT INCENTIVE UNRESOLVED",
        "maximum routine `FOLLOW = 6`",
        "maximum retained `RESERVE = 4`",
        "Operational handoff gate — fail closed",
        "ASSESSMENT BLOCKED — LOW OPERATIONAL OBSERVABILITY",
        "operational viability grade A",
        "grade B can never receive routine FOLLOW",
        "competition_reliability_state",
        "CAUTION is never above B",
        "burden_completion_quality",
        "continuation_quality",
        "burden_stall_risk",
        "maximum routine `FOLLOW = 2`",
        "Command alias:** `/rank`",
        "FOOTBALL_WOMENS_TOP_FLIGHT_COVERAGE.md",
        "women_top_flight_disposition_manifest",
        "WOMEN TOP-FLIGHT COVERAGE GAP",
    ],
    "models/football/prompts/02_NORMAL_CHAT_XI_ODDS.md": [
        "Football C Official + C2 Shadow XI/Odds",
        "MANDATORY FRESH POST-XI FOOTBALL WEB RESEARCH",
        "Odds/history lookup does **not** satisfy the football-research gate.",
        "Football C official action",
        "Follow-through lane authority",
        "`STOP` — do not run routine Step-2",
        "Football C2 shadow action",
        "Only Football C may create official exposure.",
        "FOOTBALL_ENGINE_C_DECISION_INPUT",
        "FOOTBALL_ENGINE_C2_DECISION_INPUT",
        "ENGINE DISAGREEMENT",
        "DECISION BLOCKED — TOURNAMENT INCENTIVE RECHECK MISSING",
        "tournament_incentive_rechecked",
        "tournament_incentive_recheck_status",
        "DECISION BLOCKED — TOURNAMENT INCENTIVE UNRESOLVED",
        "frozen operational viability grade",
        "actual confirmed/reliable XI",
        "Recheck the burden-completion layer",
        "Current continuation quality + opponent leakage + stall risk",
        "Current Completion Mode",
        "Current Stall Risk",
        "Command alias:** `/xi`",
    ],
    "models/football/prompts/03_NORMAL_CHAT_LIVE.md": [
        "Football C Official Live + C2 Shadow Wait",
        "TARGET REACHED + THESIS STILL HEALTHY?",
        "C-WAIT CANCELLED — THESIS DECAY",
        "C2 may never create Website Pick or real exposure.",
        "LIVE DECISION BLOCKED — TOURNAMENT INCENTIVE EPOCH MISSING",
        "Command alias:** `/live`",
    ],
    "models/football/prompts/04_WORK_POST_SLATE_AUDIT.md": [
        "C OFFICIAL BOARD -> FOLLOW/RESERVE/STOP -> C2 SHADOW BOARD",
        "mandatory post-XI football research",
        "Confirmatory C-vs-C2 counting restarts",
        "Historical Football A/C1 audits remain version-faithful.",
        "FOLLOW/RESERVE/STOP allocation",
        "tournament-incentive completeness",
        "Competition reliability memory update — mandatory",
        "Competition Reliability Events",
        "never write FT goals, C/C2 result, settlement or P/L",
        "women\'s senior top-flight discovery/accounting misses",
        "WOMEN TOP-FLIGHT COVERAGE GAP",
        "Command alias:** `/audit`",
    ],
    "models/football/challengers/football-c2/FOOTBALL_C2_SPEC.md": [
        "**Champion:** Football C",
        "Dual-track operational boundary",
        "C2 may not create Website Picks or real exposure.",
    ],
    "models/football/challengers/football-c2/TEST_PROTOCOL.md": [
        "**Champion:** Football C",
        "C-vs-C2",
        "Restart boundary",
    ],
    "models/football/engine/competition_reliability.py": [
        "def evaluate_competition_reliability",
        "def apply_reliability_cap",
        "def effective_state",
        "COUNTABLE_TYPES",
        "DEMOTED",
        "CAUTION",
    ],
    "models/football/engine/schema.json": [
        "football-engine-v1",
        "\"stage\"",
        "\"matches\"",
        "\"context\"",
        "\"tournament_incentive_required\"",
        "\"tournament_incentive_rechecked\"",
        "\"tournament_incentive_recheck_status\"",
        "\"operational_viability_grade\"",
        "\"xi_expected\"",
        "\"market_observability\"",
        "\"team_news_observability\"",
        "\"raw_operational_viability_grade\"",
        "\"competition_reliability_state\"",
        "\"competition_reliability_reason\"",
        "\"competition_reliability_manual_override\"",
        "\"demoted_probation\"",
        "\"qualification_state\"",
        "\"simultaneous_results_status\"",
        "\"kickoff_ict\"",
        "\"completion_mode\"",
        "\"burden_completion_quality\"",
        "\"continuation_quality\"",
        "\"opponent_leakage\"",
        "\"burden_stall_risk\"",
    ],
    "models/football/trials/FOOTBALL_C_ELITE_UPPER_TAIL_OBSERVER_2026-10-01.md": [
        "PROSPECTIVE OBSERVER ONLY — NO PRODUCTION AUTHORITY",
        "ELITE_UPPER_TAIL_OBSERVER",
        "does not extend the C2 bridge",
    ],
    "models/football/engine/adapter.py": [
        "def run_board",
        "follow_through_lane",
        "MAX_FOLLOW = 6",
        "MAX_RESERVE = 4",
        "def run_decision",
        "SCHEMA_VERSION = \"football-engine-v1\"",
        "validate_tournament_incentive",
        "DECISION BLOCKED — TOURNAMENT INCENTIVE RECHECK MISSING",
        "validate_operational_viability",
        "ASSESSMENT BLOCKED — LOW OPERATIONAL OBSERVABILITY",
        "operational_gate[\"grade\"] == \"B\"",
        "apply_reliability_cap",
        "effective_state",
        "COMPETITION RELIABILITY CAP BYPASS",
        "MAX_FOLLOW_PER_KICKOFF = 2",
        "C-PASS CONTRADICTION",
        "same_kickoff_rank",
        "rank_assessments_c2",
        "c2_ranking_key(item)",
    ],
}

failures = []
for file_name, needles in REQUIRED.items():
    path = Path(file_name)
    if not path.exists():
        failures.append(f"{file_name}: missing file")
        continue
    text = path.read_text(encoding="utf-8")
    for needle in needles:
        if needle not in text:
            failures.append(f"{file_name}: missing invariant: {needle}")

if failures:
    print("WORKFLOW REGRESSION — FOOTBALL C/C2 DUAL-TRACK INVARIANT MISSING")
    for failure in failures:
        print(f"- {failure}")
    sys.exit(1)

print("PASS — Football C official / C2 shadow / engine dual-track invariants are present.")
